### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by justinliu1985** [MicroWebStacks/astro-big-doc#1]
I downloaded the entire folder, ran dev.cmd, and reported error.
![image](https://user-images.githubusercontent.com/105055890/222659720-9f0f4f15-f488-4c06-a2a9-edce3db821d4.png)

**Comment by wassfila** [comment]
thanks for reporting this, there was no support of zero config build, but now I made sure it properly builds in static by default and no errors if base config is undefined.
so this is now fixed with 1ac30d7

**Comment by wassfila** [comment]
I also documented the Environment variables usage now https://github.com/MicroWebStacks/astro-big-doc#env-config
